# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 772cc965717da9b712c8ff9deaa8fb2b8180fcd7647fe235032f685545eadfa65a46e9a6132015b21e52f57fb2ff5235b1ff2c3b430a858c59bc91e07bce4ec1

test:
  secret_key_base: faa5ccaf282c3dbafc832081ef4ec7693a4465ea96aa126acbbc70ff2d3be0c2ff7a564f924c22c9d1dcf7b34fbf4c5e534aa0961bc40c46297626e2849c919f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
